// ActionType.js

const ActionType = {
  RECEIVE_NOTE: 'RECEIVE_NOTE',
  FETCHING_NOTE_PENDING: 'FETCHING_NOTE_PENDING',
  FETCHING_NOTE_REJECTED: 'FETCHING_NOTE_REJECTED',

  // Authentication
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_PENDING: 'AUTH_PENDING',
  AUTH_FAIL: 'AUTH_FAIL',
  HIDE_ERROR: 'HIDE_ERROR',

  // Products action
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  FETCHING_PRODUCTS_PENDING: 'FETCHING_PRODUCTS_PENDING',
  FETCHING_PRODUCTS_REJECTED: 'FETCHING_PRODUCTS_REJECTED',

  // Product info action
  RECEIVE_PRODUCT_INFO: 'RECEIVE_PRODUCT_INFO',
  FETCHING_PRODUCT_INFO_PENDING: 'FETCHING_PRODUCT_INFO_PENDING',
  FETCHING_PRODUCT_INFO_REJECTED: 'FETCHING_PRODUCT_INFO_REJECTED',

  RECEIEVE_PRODUCTS_BY_IDS: 'RECEIEVE_PRODUCTS_BY_IDS',
  FETCHING_PRODUCTS_BY_IDS_PENDING: 'FETCHING_PRODUCTS_BY_IDS_PENDING',
  FETCHING_PRODUCTS_BY_IDS_REJECTED: 'FETCHING_PRODUCTS_BY_IDS_REJECTED',

  // Cart item action
  ADD_CART_ITEM_FULLFILLED: 'ADD_CART_ITEM_FULLFILLED',
  ADD_CART_ITEM_PENDING: 'ADD_CART_ITEM_PENDING',
  ADD_CART_ITEM_REJECTED: 'ADD_CART_ITEM_REJECTED',

  HIDE_SUCCESS_TOAST: 'HIDE_SUCCESS_TOAST',

  // Product category action
  RECEIVE_PRODUCTCATEGORY: 'RECEIVE_PRODUCTCATEGORY',
  FETCHING_PRODUCTCATEGORY_PENDING: 'FETCHING_PRODUCTCATEGORY_PENDING',
  FETCHING_PRODUCTCATEGORY_REJECTED: 'FETCHING_PRODUCTCATEGORY_REJECTED',

  // Shopping cart action
  RECEIVE_SHOPPINGCART: 'RECEIVE_SHOPPINGCART',
  FETCHING_SHOPPINGCART_PENDING: 'FETCHING_SHOPPINGCART_PENDING',
  FETCHING_SHOPPINGCART_REJECTED: 'FETCHING_SHOPPINGCART_REJECTED',
  PROCEEED_SHOPPING_CART: 'PROCEEED_SHOPPING_CART',

  // Product comments action
  RECEIVE_PRODUCT_COMMENTS: 'RECEIVE_PRODUCT_COMMENTS',
  FETCHING_PRODUCT_COMMENTS_PENDING: 'FETCHING_PRODUCT_COMMENTS_PENDING',
  FETCHING_PRODUCT_COMMENTS_REJECTED: 'FETCHING_PRODUCT_COMMENTS_REJECTED',

  // Payment actions
  PAYMENT_SUCESS: 'PAYMENT_SUCESS',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',

  // Order actions
  RECEIVE_ORDER: 'RECEIVE_ORDER',
  FETCHING_ORDER_PENDING: 'FETCHING_ORDER_PENDING',
  FETCHING_ORDER_REJECTED: 'FETCHING_ORDER_REJECTED'
}

export default ActionType;