// ActionType.js

export const ADD_COUNTER = 'ADD_COUNTER';
export const REMOVE_COUNTER = 'REMOVE_COUNTER';

const ActionType = {
  RECEIVE_NOTE: 'RECEIVE_NOTE',
  FETCHING_NOTE_PENDING: 'FETCHING_NOTE_PENDING',
  FETCHING_NOTE_REJECTED: 'FETCHING_NOTE_REJECTED',

  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_PENDING: 'AUTH_PENDING',
  AUTH_FAIL: 'AUTH_FAIL'
}

export default ActionType;