// ActionType.js

const ActionType = {
  RECEIVE_NOTE: 'RECEIVE_NOTE',
  FETCHING_NOTE_PENDING: 'FETCHING_NOTE_PENDING',
  FETCHING_NOTE_REJECTED: 'FETCHING_NOTE_REJECTED',

  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_PENDING: 'AUTH_PENDING',
  AUTH_FAIL: 'AUTH_FAIL',

  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  FETCHING_PRODUCTS_PENDING: 'FETCHING_PRODUCTS_PENDING',
  FETCHING_PRODUCTS_REJECTED: 'FETCHING_PRODUCTS_REJECTED',
}

export default ActionType;